import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { CONFIG } from '../config.mjs';
import { normalize, choose, escapeHtml, toCsv } from './core.mjs';

const root=resolve(import.meta.dirname,'..'); const output=resolve(root,'site'); const now=new Date();
async function request(category) { const url=new URL('https://api.github.com/search/repositories');url.searchParams.set('q',category.query);url.searchParams.set('sort','updated');url.searchParams.set('order','desc');url.searchParams.set('per_page',String(CONFIG.limitPerQuery));const response=await fetch(url,{headers:{'Accept':'application/vnd.github+json','User-Agent':'Opportunity-Radar/1.0'}});if(!response.ok)throw new Error(`GitHub API ${response.status} for ${category.label}`);const data=await response.json();return (data.items||[]).map(item=>normalize(item,category.label,now)); }
function dateText(value){return new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeZone:'Asia/Shanghai'}).format(new Date(value));}
function card(item,index){const home=item.homepage?`<a class="home" href="${escapeHtml(item.homepage)}" rel="nofollow noopener" target="_blank">官网</a>`:'';return `<article class="card"><div class="card-top"><span>NO. ${String(index+1).padStart(2,'0')}</span><strong>${item.score} 分</strong></div><h2><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">${escapeHtml(item.name)}</a></h2><p class="desc">${escapeHtml(item.description)}</p><div class="meta"><span>${escapeHtml(item.category)}</span><span>★ ${item.stars.toLocaleString()}</span><span>${escapeHtml(item.language)}</span><span>${escapeHtml(item.license)}</span></div><div class="links"><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">GitHub →</a>${home}</div></article>`;}
function page(items){const cards=items.length?items.slice(0,CONFIG.freeItems).map(card).join(''):'<p>本次没有找到符合许可条件的项目。</p>';return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="每日自动筛选可商用的开源软件与自动化工具。"><title>${CONFIG.siteName}</title><style>:root{--ink:#132238;--muted:#60708a;--line:#dce4ee;--blue:#155eef}*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:var(--ink);font:15px/1.6 Inter,"Microsoft YaHei",Arial,sans-serif}.wrap{max-width:1080px;margin:auto;padding:52px 22px 70px}.eyebrow{font-weight:800;letter-spacing:.13em;font-size:11px;color:var(--blue)}h1{font-size:38px;line-height:1.1;margin:8px 0}header p{color:var(--muted);max-width:660px}header{border-bottom:2px solid var(--ink);padding-bottom:28px}.stats{display:flex;gap:14px;flex-wrap:wrap;margin:25px 0}.stat{background:#eaf0ff;color:#174ea6;border-radius:999px;padding:5px 11px;font-size:12px;font-weight:700}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{border:1px solid var(--line);background:#fff;border-radius:12px;padding:19px}.card-top{display:flex;justify-content:space-between;font-size:12px;color:var(--blue);font-weight:800}.card h2{font-size:19px;line-height:1.25;margin:10px 0 7px}.card a{color:var(--ink);text-decoration:none}.card h2 a:hover,.links a:hover{text-decoration:underline}.desc{min-height:72px;color:#405069;margin:0}.meta{border-top:1px solid var(--line);margin-top:15px;padding-top:10px;display:flex;gap:8px;flex-wrap:wrap;color:var(--muted);font-size:12px}.meta span{border-radius:4px;background:#f2f5f9;padding:2px 6px}.links{display:flex;gap:14px;margin-top:15px}.links a{color:var(--blue);font-weight:800;font-size:13px}footer{border-top:1px solid var(--line);margin-top:34px;padding-top:16px;font-size:12px;color:var(--muted)}@media(max-width:650px){.wrap{padding:35px 15px}.grid{grid-template-columns:1fr}h1{font-size:30px}}</style></head><body><main class="wrap"><header><div class="eyebrow">AUTONOMOUS OPEN-SOURCE INTELLIGENCE</div><h1>${CONFIG.siteName}</h1><p>每日自动从公开数据中筛选近期活跃、许可明确、具备商业使用价值的开源工具。评分只用于发现，不构成投资、法律或商业建议。</p></header><div class="stats"><span class="stat">更新：${dateText(now)}</span><span class="stat">筛选结果：${items.length} 个</span><span class="stat">免费展示：${Math.min(items.length,CONFIG.freeItems)} 个</span></div><section class="grid">${cards}</section><footer>数据来自 GitHub 公开 API · 自动生成于 ${now.toISOString()} · 使用前请自行核对许可证和项目状态。</footer></main></body></html>`;}
const results=await Promise.all(CONFIG.queries.map(request));const items=choose(results.flat(),now);const payload={generatedAt:now.toISOString(),source:'GitHub public REST API',items};await mkdir(resolve(output,'data'),{recursive:true});await writeFile(resolve(output,'index.html'),page(items),'utf8');await writeFile(resolve(output,'data','latest.json'),JSON.stringify(payload,null,2),'utf8');await writeFile(resolve(output,'data','latest.csv'),toCsv(items),'utf8');await writeFile(resolve(output,'feed.xml'),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${CONFIG.siteName}</title><link>https://example.invalid/</link><description>每日自动更新的开源商业机会。</description><lastBuildDate>${now.toUTCString()}</lastBuildDate>${items.slice(0,10).map(item=>`<item><title><![CDATA[${item.name}]]></title><link>${item.url}</link><description><![CDATA[${item.description}]]></description><pubDate>${new Date(item.updatedAt).toUTCString()}</pubDate></item>`).join('')}</channel></rss>`,'utf8');console.log(`Generated ${items.length} items in ${output}`);
